// Code generated by gen-metrics-registrar. DO NOT EDIT.
package metricsregistrar

import (
	_ "github.com/google/exposure-notifications-verification-server/internal/clients"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/appsync"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/backup"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/certapi"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/cleanup"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/e2erunner"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/emailer"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/issueapi"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/modeler"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/rotation"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/statspuller"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/user"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/userreport"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/verifyapi"
	_ "github.com/google/exposure-notifications-verification-server/pkg/controller/webhooks"
	_ "github.com/google/exposure-notifications-verification-server/pkg/database"
	_ "github.com/google/exposure-notifications-verification-server/pkg/ratelimit/limitware"
)
