# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Runs schema migrations.
#

substitutions:
  _DB_CONN:
  _DB_NAME: 'verification'
  _DB_PASS_SECRET:
  _DB_PORT: '5432'
  _DB_HOST: 'localhost'
  _DB_SSLMODE: 'disable'
  _DB_USER: 'verification'

steps:
- id: 'secrets'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:296.0.1-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud secrets versions access "${_DB_PASS_SECRET}" > ./db-password

- id: 'migrate'
  name: 'golang:1.14'
  env:
  - 'DB_NAME=${_DB_NAME}'
  - 'DB_USER=${_DB_USER}'
  - 'DB_HOST=${_DB_HOST}'
  - 'DB_PORT=${_DB_PORT}'
  - 'DB_SSLMODE=${_DB_SSLMODE}'
  entrypoint: '/bin/bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    echo "==> Configuring proxy"
    wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /bin/cloud_sql_proxy
    chmod +x /bin/cloud_sql_proxy
    /bin/cloud_sql_proxy -quiet -instances=${_DB_CONN}=tcp:${_DB_PORT} &
    sleep 5

    echo "==> Running migrations"
    export DB_PASSWORD="$(cat ./db-password)"
    go run cmd/migrate/main.go
