# Copyright 2020 the Exposure Notifications Verification Server authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Promotes the revision of a service to receive 100% of traffic.
#

substitutions:
  _PERCENTAGE:
  _REGION:
  _REVISION:

steps:
#
# adminapi
#
- id: 'promote-adminapi'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "adminapi" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# apiserver
#
- id: 'promote-apiserver'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "apiserver" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# appsync
#
- id: 'promote-appsync'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "appsync" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# backup
#
- id: 'promote-backup'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "backup" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# cleanup
#
- id: 'promote-cleanup'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "cleanup" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# e2e-runner
#
- id: 'promote-e2e-runner'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "e2e-runner" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# enx-redirect
#
- id: 'promote-enx-redirect'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "enx-redirect" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# modeler
#
- id: 'promote-modeler'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "modeler" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# metrics-registrar
#
- id: 'promote-metrics-registrar'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "metrics-registrar" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# rotation
#
- id: 'promote-rotation'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "rotation" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'

#
# server
#
- id: 'promote-server'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "server" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'


#
# stats-puller
#
- id: 'promote-stats-puller'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:335.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run services update-traffic "stats-puller" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --to-revisions "${_REVISION}=${_PERCENTAGE}"
  waitFor:
  - '-'
