#!/usr/bin/env bash

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

if [ -z "${DB_CONN:-}" ]; then
  echo "✋ Missing DB_CONN (e.g. my-project:us-central1:my-database)!" >&2
  exit 1
fi

if [ -z "${DB_ENCRYPTION_KEY:-}" ]; then
  echo "✋ Missing DB_ENCRYPTION_KEY (e.g. projects/my-project/locations/us-east1/keyRings/my-kr/cryptoKeys/my-key)!" >&2
  exit 1
fi

if [ -z "${DB_APIKEY_DATABASE_KEY:-}" ]; then
  echo "✋ Missing DB_APIKEY_DATABASE_KEY (e.g. secret://projects/my-project/secrets/my-secret/versions/1)!" >&2
  exit 1
fi

if [ -z "${DB_APIKEY_SIGNATURE_KEY:-}" ]; then
  echo "✋ Missing DB_APIKEY_SIGNATURE_KEY (e.g. secret://projects/my-project/secrets/my-secret/versions/1)!" >&2
  exit 1
fi

if [ -z "${DB_VERIFICATION_CODE_DATABASE_KEY:-}" ]; then
  echo "✋ Missing DB_VERIFICATION_CODE_DATABASE_KEY (e.g. secret://projects/my-project/secrets/my-secret/versions/1)!" >&2
  exit 1
fi

if [ -z "${DB_PASSWORD:-}" ]; then
  echo "✋ Missing DB_PASSWORD (e.g. secret://projects/my-project/secrets/my-secret/versions/1)!" >&2
  exit 1
fi

if [ -z "${DB_NAME:-}" ]; then
  DB_NAME="verification"
  echo "🚧 Using database \"${DB_NAME}\"" >&2
fi

if [ -z "${DB_USER:-}" ]; then
  DB_USER="verification"
  echo "🚧 Using username \"${DB_USER}\"" >&2
fi

SUBS="_DB_CONN=${DB_CONN}"
SUBS="${SUBS},_DB_APIKEY_DATABASE_KEY=${DB_APIKEY_DATABASE_KEY}"
SUBS="${SUBS},_DB_APIKEY_SIGNATURE_KEY=${DB_APIKEY_SIGNATURE_KEY}"
SUBS="${SUBS},_DB_VERIFICATION_CODE_DATABASE_KEY=${DB_VERIFICATION_CODE_DATABASE_KEY}"
SUBS="${SUBS},_DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY}"
SUBS="${SUBS},_DB_NAME=${DB_NAME}"
SUBS="${SUBS},_DB_PASSWORD=${DB_PASSWORD}"
SUBS="${SUBS},_DB_USER=${DB_USER}"
SUBS="${SUBS},_DB_DEBUG=${DB_DEBUG}"
SUBS="${SUBS},_LOG_DEBUG=${LOG_DEBUG}"

gcloud builds submit "${ROOT}" \
  --config "${ROOT}/builders/migrate.yaml" \
  --substitutions "${SUBS}" \
  --project "${PROJECT_ID}"
